server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          mcp-client:
            registration:
              client-id: "mcp-auth-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_post"
              authorization-grant-types:
                - "client_credentials"
              scopes:
                - "openid"
                - "profile"
                - "mcp.tools"
            require-authorization-consent: true
